from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to

urlspatterns = patterns('',
    url('2011/07/21/introducing-the-security-blanket/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home/introducing-the-security-blanket_800', 'permanent': True}),
    url('2011/07/26/crime-statistics-describe-how-burglars-break-in/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/crime-statistics-describe-how-burglars-break-in_802', 'permanent': True}),
    url('2011/08/01/weird-strange-and-uncommon-home-security-devices/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-equipment/weird-strange-and-uncommon-home-security-devices_62', 'permanent': True}),
    url('2011/08/09/before-you-go-home-security-tips-for-a-worry-free-vacation/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/before-you-go-home-security-tips-for-a-worry-free-vacation_82', 'permanent': True}),    url('2011/08/11/making-a-bb-gun-booby-trap-a-home-security-expert-analyzes-%E2%80%9Chome-alone%E2%80%9D/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/making-a-bb-gun-booby-trap-a-home-security-expert-analyzes-home-alone_108', 'permanent': True}), 
    url('2011/08/18/best-home-security-diy-projects-and-quick-tips/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/best-home-security-diy-projects-and-quick-tips_148', 'permanent': True}),
    url('2011/08/23/summer-fire-safety-tips-for-kids/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/summer-fire-safety-tips-for-kids_171', 'permanent': True}),
    url('2011/09/08/the-5-stupidest-burglars-and-robbers-to-ever-rob-a-home-ever/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-news/the-5-stupidest-burglars-and-robbers-to-ever-rob-a-home-ever_190', 'permanent': True}),
    url('2011/09/28/burglary-infographic/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/burglary-infographic_284', 'permanent': True}),
    url('2011/09/29/get-to-know-your-criminal-the-different-types-of-burglar/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/get-to-know-your-criminal-the-different-types-of-burglar_228', 'permanent': True}),
    url('2011/10/10/its-fire-prevention-week/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home/its-fire-prevention-week_299', 'permanent': True}),
    url('2011/10/12/how-to-make-a-fire-evacuation-plan-for-your-home/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/how-to-make-a-fire-evacuation-plan-for-your-home_306', 'permanent': True}),
    url('2011/10/24/superhero-or-superzero/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-news/superhero-or-superzero_320', 'permanent': True}),
    url('2011/11/02/study-4-out-of-5-burglars-use-social-networks-to-find-empty-houses/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/study-4-out-of-5-burglars-use-social-networks-to-find-empty-houses_349', 'permanent': True}),
    url('2011/11/07/social-networking-and-burglary-infographic/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/social-networking-and-burglary-infographic_372', 'permanent': True}),
    url('2011/11/10/new-study-highlights-effectiveness-of-smoke-alarms/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/new-study-highlights-effectiveness-of-smoke-alarms_383', 'permanent': True}),
    url('2011/11/15/awesome-home-security-devices/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/uncategorized/awesome-home-security-devices_405', 'permanent': True}),
    url('2011/11/16/amazing-video-of-a-home-owner-protecting/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/miscellaneous/amazing-video-of-a-home-owner-protecting_468', 'permanent': True}),
    url('2011/11/30/lower-penalties-for-burglars-states-ease-sentences-for-felony-property-crimes/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-news/lower-penalties-for-burglars-states-ease-sentences-for-felony-property-crimes_472', 'permanent': True}),
    url('2011/12/01/kansas-criminal-takes-hostages-later-sues-victims/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/miscellaneous/kansas-criminal-takes-hostages-later-sues-victims_498', 'permanent': True}),
    url('2011/12/07/ez-armor-review-home-security-that-starts-at-the-front-door/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/uncategorized/ez-armor-review-home-security-that-starts-at-the-front-door_508', 'permanent': True}),
    url('2011/12/19/holiday-home-security-tips-for-students/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/miscellaneous/holiday-home-security-tips-for-students_523', 'permanent': True}),
    url('2012/01/04/actress-lindsay-lohan-looking-to-upgrade-home-security/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/miscellaneous/actress-lindsay-lohan-looking-to-upgrade-home-security_532', 'permanent': True}),
    url('2012/01/12/the-best-apps-for-crime-statistics-and-home-security-planning/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/miscellaneous/the-best-apps-for-crime-statistics-and-home-security-planning_542', 'permanent': True}),
    url('2012/01/17/home-security-guns-and-horror-movie-the-perfect-solution/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/miscellaneous/home-security-guns-and-horror-movie-the-perfect-solution_564', 'permanent': True}),
    url('2012/01/25/drugstores-and-pharmacies-required-to-increase-security-measures/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/miscellaneous/drugstores-and-pharmacies-required-to-increase-security-measures_569', 'permanent': True}),
    url('2012/01/26/security-providers-fight-for-republican-national-convention-contract/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/security-providers-fight-for-republican-national-convention-contract_626', 'permanent': True}),
    url('2012/01/27/ice-your-family-and-friends-in-case-of-emergency-numbers/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/ice-your-family-and-friends-in-case-of-emergency-numbers_562', 'permanent': True}),
    url('2012/01/30/home-security-camera-busts-ups-driver/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/home-security-camera-busts-ups-driver_652', 'permanent': True}),
    url('2012/02/01/burrito-chain-security-camera-footage-goes-viral/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-news/burrito-chain-security-camera-footage-goes-viral_659', 'permanent': True}),
    url('2012/02/03/arizona-man-caught-on-camera-with-stolen-spiders-in-his-pants/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-news/arizona-man-caught-on-camera-with-stolen-spiders-in-his-pants_668', 'permanent': True}),
    url('2012/02/13/sht-burglars-say-an-original-video-from-protect-america/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/miscellaneous/sht-burglars-say-an-original-video-from-protect-america_676', 'permanent': True}),
    url('2012/02/14/list-of-americas-largest-home-security-companies/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/list-of-americas-largest-home-security-companies_577', 'permanent': True}),
    url('2012/02/23/home-security-robots-the-future-is-wow/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/home-security-robots-the-future-is-wow_690', 'permanent': True}),
    url('2012/03/06/burglar-alarms-can-lead-to-lower-crime-rates-says/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/burglar-alarms-can-lead-to-lower-crime-rates-says_726', 'permanent': True}),
    url('2012/03/07/girl-scouts-robbed-of-cookie-money/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-news/girl-scouts-robbed-of-cookie-money_733', 'permanent': True}),
    url('2012/03/22/home-security-systems-can-drop-crime-by-10-percent-says-orlandos-top-cop/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-news/home-security-systems-can-drop-crime-by-10-percent-says-orlandos-top-cop_684', 'permanent': True}),
    url('2012/03/23/home-defense-tips-and-techniques/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-defense-advice/home-defense-tips-and-techniques_740', 'permanent': True}),
    url('2012/04/02/sorry-sacks-steal-seuss-statue/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-news/sorry-sacks-steal-seuss-statue_758', 'permanent': True}),
    url('2012/04/04/crime-prevention-tips-from-colorado-cops/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/crime-prevention-tips-from-colorado-cops_769', 'permanent': True}),
    url('2012/04/06/real-life-hamburglar-bloodies-self-stealing-frozen-patties/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-news/real-life-hamburglar-bloodies-self-stealing-frozen-patties_776', 'permanent': True}),
    url('2012/04/16/list-of-home-protection-providers-in-america/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/list-of-home-protection-providers-in-america_783', 'permanent': True}),
    url('2012/04/26/crime-statistics-by-neighborhood/',
        redirect_to, {'url': 'http://www.protectamerica.com/home-security-blog/home-security/home-security-information/crime-statistics-by-neighborhood_809', 'permanent': True}),
)    
