SITE_ID = 14

DEFAULT_AGENT = 'i10123'
DEFAULT_SOURCE = 'Canada (Organic)'

from settings import *

#del SESSION_COOKIE_DOMAIN
DEFAULT_PHONE = '8774597521'
CACHES['default']['KEY_PREFIX'] = 'SITE_ID_14__'